name: Deploy DEV

on:
    push:
        branches: ['dev']
    pull_request:
        branches: ['dev']

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - run: npm install
            - run: npm run build
            - run: npm install pm2@latest -g
            - run: pm2 -V
            - run: pm2 list
            - run: pm2 start ./dist/index.js --name=api-dev --watch
            - run: ip a
